# Generated by Django 3.1 on 2020-08-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
